
# Setting PATH for Python 3.10
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:${PATH}"
export PATH

export PATH="/Users/tushar.dwivedi/.local/share/solana/install/active_release/bin:$PATH"
