{
 "title": "CDC Publisher P0",
 "tags": [ "callisto" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": "*" },
   { "name": "Datasource", "label": "Datasource", "query": "graphite" },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Customer", "label": "Customer", "query": "tags.cluster.*" },
   { "name": "ClusterTag", "label": "ClusterTag", "query": "tags.cluster.$Customer.*" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "tags.cluster.$Customer.$ClusterTag.*"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Publisher Service Restarts",
   "type": "stat",
   "description": "Number of time CDC Publisher service is restarted in the given time span.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.Diamond.service.CDCDataPublisher.Run.count),\"sum\",1)"
    }
   ]
  },
  { "title": "API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Stream API Calls",
   "type": "timeseries",
   "description": "Number of live stream related API calls in the selected interval.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.subscribe_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.unsubscribe_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.subscribe_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.unsubscribe_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Fetch (Full/Incremental) API Calls & EOS",
   "type": "timeseries",
   "description": "Number of fetch related API calls in the selected interval.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_full_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_full_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_incremental_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_incremental_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.state_SUCCESS.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.count), '${interval}', 'sum'), 0, 3, 4)"
    }
   ]
  },
  { "title": "Events Published", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Events Published (Live v/s Backfill)",
   "type": "timeseries",
   "description": "Comparison between live stream and backfill events (indicates how much repeated work the system has to do)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.live_events_published.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.backfill_events_published.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Events published (by message type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.data_events_published.count), '${interval}', 'sum'), 'data_events_published')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.count), '${interval}', 'sum'), 'eos_events_published')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.heartbeat_events_published.count), '${interval}', 'sum'), 'heartbeat_events_published')"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.*.count), '${interval}', 'sum'), 3, 4)"
    }
   ]
  },
  {
   "title": "Data Events Push Failed (by stream types)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.live_data_events_failed_to_publish.count), '${interval}', 'sum'), 'live_data_events_failed_to_publish')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.full_replay_data_events_failed_to_publish.count), '${interval}', 'sum'), 'full_replay_data_events_failed_to_publish')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.inc_replay_data_events_failed_to_publish.count), '${interval}', 'sum'), 'inc_replay_data_events_failed_to_publish')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.dga_push_failed_after_retries.count), '${interval}', 'sum'), 'dga_push_total_failed_after_retries')"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Live Events E2E Latencies",
   "type": "timeseries",
   "description": "End to End latencies of live events published via CDC Publisher",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.75-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.50-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Backfill Events E2E Latencies",
   "type": "timeseries",
   "description": "End to End latencies of backfill events published via CDC Publisher",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.99-percentile, 'backfill_events_e2e_p99'"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.97-percentile, 'backfill_events_e2e_p75')5"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.50-percentile, 'backfill_events_e2e_p50')"
    }
   ]
  },
  {
   "title": "Replay/Delete Work E2E Latencies",
   "type": "timeseries",
   "description": "E2E latencies of replay works (& delete works)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_e2e_delay.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_e2e_delay.99-percentile, 0, 3, 4)"
    }
   ]
  },
  { "title": "Replays (Full & Incremental)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Replay & Delete Events Generated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_upsert_events_generated), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_upsert_events_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_delete_events_generated.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_delete_events_count.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Replay works (Retry/Reassign/Empty)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_reassignment_count.count), '${interval}', 'sum'), 'Reassigned Replay works')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.restarted_replay_work_count.count), '${interval}', 'sum'), 'Replay works restarted at startup')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_works_retried_count.count), '${interval}', 'sum'), 'Delete works retried')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.empty_replay_work_count.count), '${interval}', 'sum'), 'Empty Replay works ')"
    }
   ]
  },
  {
   "title": "Replay work events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_data_event_loss_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.full_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.inc_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  }
 ]
}