{
 "title": "CDC Publisher Debug",
 "tags": [ "callisto" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": "*" },
   { "name": "Datasource", "label": "Datasource", "query": "graphite" },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Customer", "label": "Customer", "query": "tags.cluster.*" },
   { "name": "ClusterTag", "label": "ClusterTag", "query": "tags.cluster.$Customer.*" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "tags.cluster.$Customer.$ClusterTag.*"
   }
  ]
 },
 "panels": [
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Publisher Service Restarts",
   "type": "stat",
   "description": "Number of time CDC Publisher service is restarted in the given time span.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.Diamond.service.CDCDataPublisher.Run.count),\"sum\",1)"
    }
   ]
  },
  {
   "title": "Who is the coordinator?",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.coordinator.active_coordinator.value, 0, 3)"
    }
   ]
  },
  {
   "title": "Coordinator Restarts",
   "type": "stat",
   "description": "Number of times Coordinator component loop was run.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "sum",
      "mean"
     ]
    }
   },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.coordinator.coordinator_component_restart_count.count), 'sum', 1)"
    }
   ]
  },
  {
   "title": "Publisher Restarts",
   "type": "stat",
   "description": "Number of times Publisher component loop was run.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "sum",
      "mean"
     ]
    }
   },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.publisher_component_restart_count.count), 'sum', 1)"
    }
   ]
  },
  {
   "title": "Live Scanner Restarts",
   "type": "stat",
   "description": "Number of times Live Stream component loop was run.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "sum",
      "mean"
     ]
    }
   },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.live_stream_scanner.live_stream_scanner_restarts.count), 'sum', 1)"
    }
   ]
  },
  {
   "title": "Secondary Scanner Restarts",
   "type": "stat",
   "description": "Number of times Secondary Scanner component loop was run.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "sum",
      "mean"
     ]
    }
   },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.secondary_stream_scanner.secondary_stream_scanner_restarts.count), 'sum', 1)"
    }
   ]
  },
  {
   "title": "Delete Scanner Restarts",
   "type": "stat",
   "description": "Number of times Delete Scanner component loop was run.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": {
    "reduceOptions": {
     "calcs": [
      "sum",
      "mean"
     ]
    }
   },
   "targets": [
    {
     "target": "groupByNodes(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.delete_scanner.delete_scanner_restarts.count), 'sum', 1)"
    }
   ]
  },
  { "title": "Live Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Live Events E2E Latencies",
   "type": "timeseries",
   "description": "End to End latencies of live events published via CDC Publisher",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.75-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.e2e.live_events_e2e_delay_in_secs.50-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Backfill Events E2E Latencies",
   "type": "timeseries",
   "description": "End to End latencies of backfill events published via CDC Publisher",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.99-percentile, 'backfill_events_e2e_p99'"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.97-percentile, 'backfill_events_e2e_p75')5"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.backfill_events_e2e_delay_in_secs.50-percentile, 'backfill_events_e2e_p50')"
    }
   ]
  },
  {
   "title": "Heartbeat Events E2E Latencies",
   "type": "timeseries",
   "description": "End to End latencies of backfill events published via CDC Publisher",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.heartbeat_events_e2e_delay_in_secs.99-percentile, 'backfill_events_e2e_p99'"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.heartbeat_events_e2e_delay_in_secs.75-percentile, 'backfill_events_e2e_p75')"
    },
    {
     "target": "alias(clusters.$Cluster.$Node.cdc_publisher.e2e.heartbeat_events_e2e_delay_in_secs.50-percentile, 'backfill_events_e2e_p50')"
    }
   ]
  },
  {
   "title": "Live stream statuses",
   "type": "timeseries",
   "description": "Status that live streams were at any given time (0 means that there were no status changes in that time duration)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "clusters.$Cluster.$Node.cdc_publisher.metadata_stream.live_stream_current_status.*.value"
    }
   ]
  },
  { "title": "Time Continuity Enforcer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "TCE Existing Work completion",
   "type": "timeseries",
   "description": "Time Continuity Enforcer first tries to complete any abruptly stopped work assignments from any previous run. This is an indicator of repeated work to be done, before we can move on to recent work assignments.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.pre_existing_work_completion_time_in_millis.value, 0, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.pre_existing_work_completed.count, 0, 3)"
    }
   ]
  },
  {
   "title": "Events Published (Live v/s Backfill)",
   "type": "timeseries",
   "description": "Comparison between live stream and backfill events (indicates how much repeated work the system has to do)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.live_events_published.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.backfill_events_published.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Timeline hole filling",
   "type": "timeseries",
   "description": "This panel gives a comparison between the total timespan over which holes in the timeline are spread, v/s how much of them are we able to fill (both are gauge metrics). A continuous spread between the two indicates that we are not able to fill the holes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.holes_timespan.value, 0, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.holes_filled_timespan.value, 0, 3)"
    }
   ]
  },
  {
   "title": "Events Scanned (Live Stream Scanner)",
   "type": "timeseries",
   "description": "Number of events scanned by live stream scanner",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.live_stream_scanner.live_data_events_scanned.value, 0, 2, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.live_stream_scanner.live_cp_events_scanned.value, 0, 2, 3)"
    }
   ]
  },
  {
   "title": "Scanner timeline task commits",
   "type": "timeseries",
   "description": "Number of tasks that Scanners are committing to the database",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.live_stream_scanner.tasks_committed_for_primary_timeline.value, 0, 2, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.secondary_stream_scanner.tasks_committed_for_secondary_timeline.count), '${interval}', 'sum'), 0, 2, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.delete_scanner.tasks_committed_for_delete_timeline.count), '${interval}', 'sum'), 0, 2, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.live_stream_scanner.primary_timelines_dropped.count), '${interval}', 'sum'), 0, 2, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.secondary_stream_scanner.secondary_timelines_dropped.count), '${interval}', 'sum'), 0, 2, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.delete_scanner.delete_timelines_dropped.count), '${interval}', 'sum'), 0, 2, 3)"
    }
   ]
  },
  {
   "title": "Timeline commit failures",
   "type": "timeseries",
   "description": "This panel tracks the failure counts, while committing tasks to the timeline (database)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.timeline_manager.primary_timeline_commit_failure.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.timeline_manager.iteration_failure.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.holes.value, 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.timeline_manager.delete_timeline_commit_failure.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.timeline_manager.liveness_timeline_commit_failure.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.timeline_manager.secondary_timeline_commit_failure.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "TCE Task Graph",
   "type": "timeseries",
   "description": "Size of the TCE graph, and time taken to complete its various stages.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.task_graph_creation_time_in_millis.value, 0, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.task_graph_completion_time_in_millis.value, 0, 3)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.time_continuity_enforcer.task_graph_size.value, 0, 3)"
    }
   ]
  },
  {
   "title": "Replay (Full & Incremental) Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Fetch (Full/Incremental) API Calls & EOS",
   "type": "timeseries",
   "description": "Number of fetch related API calls in the selected interval, and the count of their respective EOS messages.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_full_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_full_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_incremental_api_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.fetch_incremental_api_count.failed.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.state_SUCCESS.count), '${interval}', 'sum'), 0, 3, 4)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.eos_events_published.count), '${interval}', 'sum'), 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Replay Stream State Durations",
   "type": "timeseries",
   "description": "Time spent by replay streams in each state (waiting, active, finishing)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_waiting_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_waiting_time.75-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_active_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_active_time.75-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_finishing_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.stream_finishing_time.75-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Delete Events (Scanned -> SQLite)",
   "type": "timeseries",
   "description": "Delete events that were generated, and those that were committed to SQLite database (and failures)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.delete_scanner.delete_events_persisted_to_sql_lite.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.delete_scanner.delete_events_failed_persisting_to_sql_lite.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_delete_events_generated.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_delete_events_count.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Replay & Delete Events Generated",
   "type": "timeseries",
   "description": "Number of replay and delete events generated",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_upsert_events_generated.count), ''${interval}'', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_upsert_events_count.count), ''${interval}'', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_delete_events_generated.count), ''${interval}'', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_delete_events_count.count), ''${interval}'', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Replay & Delete Events Published",
   "type": "timeseries",
   "description": "Number of replay and delete events published to DGA",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.full_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.inc_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  { "title": "Replay Works", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Replay works (Retry/Reassign/Empty)",
   "type": "timeseries",
   "description": "Number of retried and reassigned replay works.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_reassignment_count.count), '${interval}', 'sum'), 'Reassigned Replay works')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.restarted_replay_work_count.count), '${interval}', 'sum'), 'Replay works restarted at startup')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_works_retried_count.count), '${interval}', 'sum'), 'Delete works retried')"
    },
    {
     "target": "alias(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.empty_replay_work_count.count), '${interval}', 'sum'), 'Empty Replay works ')"
    }
   ]
  },
  {
   "title": "Replay/Delete Work E2E Latencies",
   "type": "timeseries",
   "description": "E2E latencies of replay works (& delete works)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_e2e_delay.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_e2e_delay.99-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Replay upsert events generated and dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_upsert_events_generated.count), ''${interval}'', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.dropped_replay_upsert_events_count.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Replay Work Lifecycle durations (wait/queued/processing)",
   "type": "timeseries",
   "description": "Time taken by replay works in various stages of their lifecycle",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_wait_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_queued_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_processing_time.*.99-percentile, 0, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_iteration_delay.99-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Delete Work Lifecycle durations (wait/queued/processing)",
   "type": "timeseries",
   "description": "Time taken by delete works in various stages of their lifecycle",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "targets": [
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_wait_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_queued_time.99-percentile, 0, 3, 4)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_processing_time.*.99-percentile, 0, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.delete_work_iteration_delay.99-percentile, 0, 3, 4)"
    }
   ]
  },
  {
   "title": "Replay work events lost and published",
   "type": "timeseries",
   "description": "Number of replay events lost, and full/incremental events published",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_data_event_loss_count.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.full_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    },
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.publisher.inc_replay_events_published.count), '${interval}', 'sum'), 0, 3)"
    }
   ]
  },
  {
   "title": "Replay work status durations",
   "type": "timeseries",
   "description": "Time spent by Replay works in each of their lifecycle status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "targets": [
    {
     "target": "aliasByNode(smartSummarize(nonNegativeDerivative(clusters.$Cluster.$Node.cdc_publisher.metadata_stream.replay_work_status.*.count), '${interval}', 'sum'), 0, 3, 4)"
    }
   ]
  }
 ]
}